
spring:
  datasource:
    url: jdbc:mysql://118.25.172.42:3306/zzjb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  redis:
    host: 118.25.172.42 
    port: 6379